export default {
 
    rowlist: {
      margin: "50px",
      marginTop: "30px",
      display: "table",
      clear: "both",
      maxWidth: "400px",
      minHeight: "680px",
      backgroundImage: " radial-gradient(#1a1919 4.2%, transparent 0)",
      backgroundSize: "40px 40px",
      width: "33.33%",
      backgroundColor: "black",
      boxShadow: "4px 3px 7px 2px #00000040",
      padding: "15px",
      borderRadius: "20px",
      float: "left",
      position: "relative",
    },
    rowlist1: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: " 70vh",
    },
    Inp: {
      border: "0",
      padding: "0px 50px",
      width: "335px",
      height: " 50px",
      fontSize: "18px",
      borderRadius: "10px",
      margin: "20px",
      position: "none",
  
  
    },
    btn: {
      height: "40px",
      width: "335px",
      border: "0",
      marginTop: "-20px",
      borderRadius: "5px",
      backgroundColor: "#e28120",
      fontWeight: "bolder",
      color: "#fff",
      cursor: "pointer",
      marginLeft: "20px",
    },
    head: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    h1: {
      width: "100%",
      marginTop: "30px",
      textAlign: "center",
      backgroundColor: "#e28120",
      borderRadius: "20% 15% 20% 20%/ 20% 20% 20%",
      padding: "0.2rem 1.2rem",
      color: "white",
    },
    paginat: {
      fontFamily: "sans-serif",
      textAlign: "center",
    },
   
    p: {
      padding: "10px",
      position: "relative",
    },
    list: {
      color: "black",
      width: "340px",
      backgroundColor: "#f4f4f2",
      height: "40px",
      margin: "30px auto",
      marginLeft: "20px",
      borderRadius: "5px",
      p: {
        padding: "10px",
        position: "relative",
      },
  
      input: {
        backgroundColor: "transparent",
        border: "0",
        color: "black",
        fontSize: "18px",
      },
    },
    del: { position: "absolute", right: "10px", cursor: "pointer" },
    nav: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: "1.5rem",
      padding: " 30px ",
      marginTop: "-60px",
    },
    bgdark: {
      backgroundColor: " #262626 !important",
    },
    date: {
      fontSize: "14px",
      fontWeight: "bold",
      color: "rgba(0,0,0,0.5)",
      marginLeft: "-60px",
    },
  
    //className city to design
    city: {
      fontSize: " 21px",
      fontWeight: "bold",
      textAlign: "center",
      textTransform: "uppercase",
      paddingTop: "5px",
      color: "rgba(0,0,0,0.7)",
    },
    temp: {
      fontSize: "40px",
      color: "rgba(0,0,0,0.9)",
      fontWeight: "80",
    },
    widget: {
      background: " linear-gradient(to bottom right, $bahamas 20%,$cabo)",
      width: "700px",
      height: "400px",
      borderRadius: "6px",
      boxShadow: "0px 60px 80px -20px $capetownShadow",
      position: "relative",
      overflow: "hidden",
    },
    details: {
      fontFamily: " Roboto, sans-serif",
      display: "flex",
      flexDirection: "column",
      marginTop: "40px",
      marginLeft: "60px",
    },
    temperature: {
      color: "Black",
      fontWeight: "200",
      fontSize: "5em",
      marginTop: "50px",
    },
    summary: {
      color: "$svalbard",
      fontSize: "2em",
      fontWeight: "300",
      width: "260px",
      marginTop: "56px",
      paddingBottom: "16px",
      borderBottom: "2px solid black",
      marginLeft: "8px",
    },
    summaryText: {
      margin: "0",
      marginLeft: "10px",
      textTransform: "uppercase",
      width: "500px",
    },
    precipitation: {
      marginTop: "16px",
      color: "$svalbard",
      fontSize: "1.6em",
      fontWeight: "300",
      marginLeft: "8px",
    },
    wind: {
      marginTop: "20px",
      color: "$svalbard",
      fontSize: "1.6em",
      fontWeight: "300",
      marginLeft: "8px",
    },
  };
  