export default {
  rowlist: {
    margin: "50px",
    marginTop: "30px",
    display: "table",
    clear: "both",
    maxWidth: "400px",
    minHeight: "680px",
    backgroundImage: " radial-gradient(#1a1919 4.2%, transparent 0)",
    backgroundSize: "40px 40px",
    width: "33.33%",
    backgroundColor: "#41403a",
    boxShadow: "4px 3px 7px 2px #00000040",
    padding: "15px",
    borderRadius: "20px",
    float: "left",
    position: "relative",
  },
  rowlist1: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: " 70vh",
  },
  Inp: {
    border: "0",
    padding: "0px 50px",
    width: "200px",
    height: " 50px",
    fontSize: "18px",
    borderRadius: "0px",
    margin: "20px",
    position: "none",
  },
  btn: {
    height: "50px",
    width: "70px",
    border: "0",
    borderRadius: "5px",
    backgroundColor: "#e28120",
    fontWeight: "bolder",
    color: "#fff",
    cursor: "pointer",
  },
  head: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  h1: {
    width: "100%",
    marginTop: "30px",
    textAlign: "center",
    backgroundColor: "#e28120",
    borderRadius: "20% 15% 20% 5%/5% 20% 15%",
    padding: "0.2rem 1.2rem",
    color: "#000000",
  },
  paginat: {
    fontFamily: "sans-serif",
    textAlign: "center",
  },
  /* list: {
    color: "black",
    width: "350px",
    backgroundColor: "rgb(180, 183, 185)",
    height: "40px",
    margin: "20px auto",
    borderRadius: "5px",
  }, */
  p: {
    padding: "10px",
    position: "relative",
  },
  list: {
    color: "black",
    width: "350px",
    backgroundColor: "rgb(180, 183, 185)",
    height: "40px",
    margin: "20px auto",
    borderRadius: "5px",
    p: {
      padding: "10px",
      position: "relative",
    },

    input: {
      backgroundColor: "transparent",
      border: "0",
      color: "black",
      fontSize: "18px",
    },
  },
  del: { position: "absolute", right: "10px", cursor: "pointer" },
  /*  nav: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "0.5rem",
    padding: " 10px 10px 0",
  }, */
  bgdark: {
    backgroundColor: " #262626 !important",
  },
  date: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "rgba(0,0,0,0.5)",
    marginLeft: "-60px",
  },

  //className city to design
  city: {
    fontSize: " 21px",
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
    paddingTop: "5px",
    color: "rgba(0,0,0,0.7)",
  },
  temp: {
    fontSize: "40px",
    color: "rgba(0,0,0,0.9)",
    fontWeight: "80",
  },
  widget: {
    background: " linear-gradient(to bottom right, $bahamas 20%,$cabo)",
    width: "700px",
    height: "400px",
    borderRadius: "6px",
    boxShadow: "0px 60px 80px -20px $capetownShadow",
    position: "relative",
    overflow: "hidden",
  },
  details: {
    fontFamily: " Roboto, sans-serif",
    display: "flex",
    flexDirection: "column",
    marginTop: "40px",
    marginLeft: "60px",
  },
  temperature: {
    color: "Black",
    fontWeight: "200",
    fontSize: "5em",
    marginTop: "50px",
  },
  summary: {
    color: "$svalbard",
    fontSize: "2em",
    fontWeight: "300",
    width: "260px",
    marginTop: "56px",
    paddingBottom: "16px",
    borderBottom: "2px solid black",
    marginLeft: "8px",
  },
  summaryText: {
    margin: "0",
    marginLeft: "16px",
    width: "660px",

    textTransform: "uppercase",
    textSize: "1px",
  },
  precipitation: {
    marginTop: "16px",
    color: "$svalbard",
    fontSize: "1.6em",
    fontWeight: "300",
    marginLeft: "8px",
  },
  wind: {
    marginTop: "20px",
    color: "$svalbard",
    fontSize: "1.6em",
    fontWeight: "300",
    marginLeft: "8px",
  },
};
